"""Generate frontend shape types from the backend's Pydantic serialization schema."""

import argparse
import json
from pathlib import Path
from typing import Any

from pydantic import TypeAdapter

from dive_trip.application.demo import DemoScenario
from dive_trip.modules.catalog.public import CatalogItem, Destination
from dive_trip.modules.planning.answer_contract import AcceptedAnswer, AnswerPlan
from dive_trip.modules.sharing.public import PublicTrip
from dive_trip.modules.trips.domain import Slot
from dive_trip.modules.trips.public import Change, ProposalDraft, Snapshot
from dive_trip.modules.trips.review import ProposalReview
from dive_trip.modules.trips.transactions import TripView


def typescript(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(
            json.dumps(item, ensure_ascii=False) for item in schema["enum"]
        )
    for union in ("anyOf", "oneOf"):
        if union in schema:
            return " | ".join(typescript(item) for item in schema[union])
    kind = schema.get("type")
    if kind in ("string", "boolean", "null"):
        return str(kind)
    if kind in ("integer", "number"):
        return "number"
    if kind == "array":
        return f"Array<{typescript(schema['items'])}>"
    if kind == "object":
        required = set(schema.get("required", []))
        properties = schema.get("properties", {})
        fields = [
            f"{json.dumps(name)}{'' if name in required else '?'}: {typescript(child)};"
            for name, child in properties.items()
        ]
        extra = schema.get("additionalProperties", False)
        if extra:
            value_type = typescript(extra) if isinstance(extra, dict) else "unknown"
            fields.append(f"[key: string]: {value_type};")
        return "{ " + " ".join(fields) + " }"
    if not schema or set(schema) <= {"title", "description", "default", "examples"}:
        return "unknown"
    raise ValueError(f"Unsupported contract schema: {schema}")


def generate() -> str:
    roots: dict[str, Any] = {
        "DestinationId": Destination,
        "DemoScenario": DemoScenario,
        "Slot": Slot,
        "CatalogItem": CatalogItem,
        "Snapshot": Snapshot,
        "Change": Change,
        "ProposalDraft": ProposalDraft,
        "ProposalReview": ProposalReview,
        "TripView": TripView,
        "PublicTrip": PublicTrip,
        "AnswerPlan": AnswerPlan,
        "AcceptedAnswer": AcceptedAnswer,
    }
    definitions: dict[str, Any] = {}
    for name, model in roots.items():
        schema = TypeAdapter(model).json_schema(mode="serialization")
        children = schema.pop("$defs", {})
        for child_name, child in children.items():
            if child_name in definitions and definitions[child_name] != child:
                raise ValueError(f"Conflicting contract: {child_name}")
            definitions[child_name] = child
        if schema.get("$ref") != f"#/$defs/{name}":
            if name in definitions and definitions[name] != schema:
                raise ValueError(f"Conflicting root: {name}")
            definitions[name] = schema
    lines = [
        "// Generated by python -m dive_trip.bootstrap.contracts. Do not edit.",
        "// Shapes only: server validators and the AcceptedAnswer runtime parser "
        "enforce semantics.",
    ]
    lines.extend(
        f"export type {name} = {typescript(schema)};"
        for name, schema in sorted(definitions.items())
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generate()
    if args.check:
        if args.output.read_text() != expected:
            raise SystemExit("GENERATED_CONTRACTS_STALE")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(expected)


if __name__ == "__main__":
    main()
